services:
  db:
    image: postgres:18
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  api-service:
    build: ./fastapi
    container_name: fastAPI_devices
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"

  api-front:
    build: ./streamlit
    container_name: streamlit_devices
    restart: always
    depends_on:
      - api-service
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8501:8501"

volumes:
  postgres_data:

